// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARe8gQ4vBw69qSEFBh0KJK2k9JHwfJU3A',
    appId: '1:776012108769:android:d1dd009b6183fb3df838a0',
    messagingSenderId: '776012108769',
    projectId: 'fir-demo-proj-a9511',
    storageBucket: 'fir-demo-proj-a9511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5TR3uC7N2Z5i_Frt_iLNBSyM5BzMyGM',
    appId: '1:776012108769:ios:0073ab7d71443acaf838a0',
    messagingSenderId: '776012108769',
    projectId: 'fir-demo-proj-a9511',
    storageBucket: 'fir-demo-proj-a9511.firebasestorage.app',
    iosClientId: '776012108769-tehd9blphmff41f7kdqfrjp3kq3a0ld3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArch2',
  );
}
